# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

target "iOS-JS-BizLogic" do
	pod 'WebViewJavascriptBridge', '~> 4.1.0'
	pod 'SLObjectiveCRuntimeAdditions', '~> 1.1.2'
	pod 'Mantle', '~> 1.4.1'
	pod 'NSString+TIUtils', :git => 'git@github.com:thirdiron/NSString-TIUtils.git'
end

target "iOS-JS-BizLogicTests" do

end

